excelpars/dashboard/urls.py
from django.conf.urls import url
from .views import home, login_view, panel, logout_view, get_id_data, edit_data, add_data, search, delete_data



urlpatterns = [
    url('^$', home, name='home'),
    url('^login/$', login_view, name='login'),
    url('^panel/$', panel, name='panel'),
    url('^logout/$', logout_view, name='logout'),
    url('^get_id_data/$', get_id_data, name='get_id_data'),
    url('^edit_data/$', edit_data, name='edit_data'),
    url('^add_data/$', add_data, name='add_data'),
    url('^search/$', search, name='search'),
    url('^delete/$', delete_data, name="delete_data"),

]

excelpars/excelpars/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^dashboard/', include('dashboard.urls'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

excelpars/dashboard/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from transliterate import translit
import uuid


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return '{}/{}'.format(instance.slug, filename)


def create_object_info_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(instance.nativeName, reversed=True))
        instance.slug = slug + '-'+uuid.uuid4().hex
        print(instance.slug)


class ObjectInfo(models.Model):

    class Meta:
        verbose_name = 'Объект'
        verbose_name_plural = 'Объекты'

    slug = models.SlugField(
        verbose_name='slugURL',
        max_length=400,
        null=True,
        blank=True
    )

    id_openData = models.CharField(
        max_length=200, 
        verbose_name='ID opendata.mkrf.ru',
        blank=True,
        null=True)

    nativeName = models.CharField(
        max_length=200,
        verbose_name='Наименование',
        blank=True,
        null=True
    )
    fullAddress = models.TextField(
        verbose_name='Полный адрес',
        blank=True,
        null=True
    )
    municipality = models.ForeignKey(
        'Municipality', 
        on_delete=models.CASCADE, 
        verbose_name='Муниципальное образование',
        blank=True,
        null=True
    )
    locality = models.ForeignKey(
        'Locality', 
        on_delete=models.CASCADE, 
        verbose_name='Населенный пункт',
        blank=True,
        null=True
    )
    
    YES = 'Yes'
    NO = 'No'
    IN_WORK = 'In_work'
    information_CHOICES = (
        (YES, 'Да'),
        (NO, 'Нет'), 
        (IN_WORK, 'На подготовке')
    )
    like_BOOLEAN = (
        (YES, 'Да'),
        (NO,  'Нет'),
    )

    OKN_in_ensemble = models.CharField(
        verbose_name='ОКН входит в ансамбль (да/нет)',
        choices=like_BOOLEAN,
        blank=True,
        null=True,
        max_length=10
     
    )
  

    information_sign = models.CharField(
        choices=information_CHOICES, 
        max_length=5,
        verbose_name='Наличие уcтановленной информационной надписи установленного образца',
        blank=True,
        null=True
    ) 
    information_sign_photo = models.ImageField(
        upload_to=image_folder, 
        blank=True,
        null=True,
        verbose_name='Фотография информационной надписи',
    )
    information_sign_conformity = models.CharField(
        verbose_name='Наличие информационной надписи, но не соответствующей требованиям',
        blank=True,
        null=True,
        choices=like_BOOLEAN,
        max_length=10

        
    )
    photo = models.ImageField(
        upload_to=image_folder, 
        blank=True,
        verbose_name='Фото',
        null=True

    )
    url = models.CharField(
        max_length=200,
        verbose_name='URL адрес',
        blank=True,
        null=True
        
    )
    description = models.TextField(
        verbose_name='Описание',
        blank=True,
        null=True
    )
    affiliation_U = models.CharField(
        choices=like_BOOLEAN,
        verbose_name='Принадлежность к ЮНЭСКО',
        blank=True,
        null=True,
        max_length=10
        
    )
    esp_valuable_object = models.CharField(
        choices=like_BOOLEAN,
        verbose_name='Особо ценный объект',
        blank=True,
        null=True,
        max_length=10
        
    )
    requisites_and_title = models.TextField(
        verbose_name=' Реквизиты и наименование акта органа государственной власти о постановке на государственную охрану объекта культурного наследия',
        blank=True,
        null=True
    )
    owner = models.CharField(
        max_length=200,
        verbose_name='Собственник',
        blank=True,
        null=True
    )
    management = models.CharField(
        max_length=200,
        verbose_name='Под чьим управлением',
        blank=True,
        null=True
    )
    owner_contacts = models.TextField(
        verbose_name='Контактные данные собственника ОКН',
        blank=True,
        null=True
    )
    has_security_obligation = models.CharField(
        choices=information_CHOICES, 
        max_length=5,
        verbose_name='Наличие охранного обязательства ОКН',
        blank=True,
        null=True
    )
    has_passport_OKN = models.CharField(
        choices=information_CHOICES, 
        max_length=5,
        verbose_name='Наличие паспорта ОКН',
        blank=True,
        null=True
    )
    actual_address = models.TextField(
        verbose_name='Актуальный адрес',
        blank=True,
        null=True
    )
    gen_species_appearance = models.ForeignKey(
        'Species', 
        on_delete=models.CASCADE,
        verbose_name='Общая видовая принадлежность',
        blank=True,
        null=True
    )
    has_docs_boundaries = models.CharField(
        choices=like_BOOLEAN,
        verbose_name='Наличие документов о границах территории ОКН',
        blank=True,
        null=True,
        max_length=10
    )
    req_of_approval = models.TextField(
        verbose_name='Реквизиты об утверждении границ территории',
        blank=True,
        null=True
        
    )
    has_docs_of_aprroval = models.CharField(
        verbose_name='Наличие документов об утвержденых зонах охраны',
        blank=True,
        null=True,
        max_length=10,
        choices=like_BOOLEAN
    )
    document_on_approved_security = models.TextField(
        verbose_name='Документ об утвержденых зонах охраны',
        blank=True,
        null=True
    )
    has_rights = models.CharField(
        verbose_name='Наличие зарегистрированных прав/обременений',
        blank=True,
        null=True,
        max_length=10,
        choices=like_BOOLEAN
    )
    date = models.DateField(
        verbose_name='Дата',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.nativeName

pre_save.connect(create_object_info_slug, sender=ObjectInfo)





class Municipality(models.Model):
    
    class Meta:
        verbose_name = 'Муниципальное образование'
        verbose_name_plural = 'Муниципальные образования'

    name = models.CharField(
        max_length=200,
        verbose_name='Муниципальное образование'
    )
 
    def __str__(self):
        return self.name



class Locality(models.Model):

    class Meta:
        verbose_name = 'Населенный пункт'
        verbose_name_plural = 'Населенные пункты'

    name = models.CharField(
        verbose_name='Населенный пункт',
        max_length=200
    )

    def __str__(self):
        return self.name


class Species(models.Model):

    class Meta:
        verbose_name = 'Видовая принадлежность'
        verbose_name_plural = 'Видовые принадлежности'

    name = models.CharField(
        verbose_name='Общая видовая принадлежность',
        max_length=200
    )
    
    def __str__(self):
        return self.name

excelpars/dashboard/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import JsonResponse
from django.db.models import Q
from .forms import LoginForm, ObjectInfoForm
from .models import ObjectInfo, Municipality, Locality, Species
from .forms import ObjectInfoForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


import json


def home(request):
    if not request.user.is_authenticated():
        return redirect(reverse('login'))
    else:
        return redirect(reverse('panel'))

    row = ObjectInfo.objects.get(id=1)
    data = print(row)
    return render(request, 'dashboard/home.html', {'text': data})


def login_view(request):
    form = LoginForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('http://127.0.0.1:8000/dashboard/panel')

    return render(request, 'dashboard/login.html', {'form': form})


@login_required
def panel(request):
    data = ObjectInfo.objects.all()
    print(list(data[:1]))
    paginator = Paginator(data, 5)

    page = request.GET.get('page')

    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    form = ObjectInfoForm()
    return render(request, 'dashboard/panel.html', {'data': data, 'form': form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('http://127.0.0.1:8000/dashboard/login')


def get_id_data(request):

    id = request.GET.get('id_row')
    row = ObjectInfo.objects.get(id=id)
    # data = serializers('json', row)
    data = serializers.serialize("json", [row, ])
    struct = json.loads(data)
    data = json.dumps(struct[0])
    # print(data)

    """data = {
        'id_openData': str(row.id_openData),
        'nativeName': str(row.nativeName),
        'fullAddress': str(row.fullAddress),
        'municipality_id': str(row.municipality_id),
        'locality_id': str(row.locality_id),
        'OKN_in_ensemble': str(row.OKN_in_ensemble),
        'information_sign': str(row.information_sign),
        'information_sign_photo': str(row.information_sign_photo),
        'information_sign_conformity': str(row.information_sign_conformity),
        'photo': str(row.photo),
        'url': str(row.url),
        'description': str(row.description),
        'affiliation_U': str(row.affiliation_U),
        'esp_valuable_object': str(row.esp_valuable_object),
        'requisites_and_title': str(row.requisites_and_title),
        'owner': str(row.owner),
        'management': str(row.management),
        'owner_contacts': str(row.owner_contacts),
        'has_security_obligation': str(row.has_security_obligation),
        'has_passport_OKN': str(row.has_passport_OKN),
        'actual_address': str(row.actual_address),
        'gen_species_appearance': str(row.gen_species_appearance),
        'has_docs_boundaries':str( row.has_docs_boundaries),
        'req_of_approval': str(row.req_of_approval),
        'has_docs_of_aprroval': str(row.has_docs_of_aprroval),
        'document_on_approved_security': str(row.document_on_approved_security),
        'has_rights': str(row.has_rights),
        'date': str(row.date),
    }"""
    # return HttpResponse(data, content_type='application/json')
    return HttpResponse(data)


def edit_data(request):
    id = request.POST.get('id_row_data')
    instance = get_object_or_404(ObjectInfo, id=id)
    if request.POST:
        form = ObjectInfoForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse('panel'))

'''
def edit_data(request):
    print(request.POST)
    
    slug = request.POST.get('slug')
    id_row_data = request.POST.get('id_row_data')
    id_openData = request.POST.get('id_openData')
    nativeName = request.POST.get('nativeName')
    fullAddress = request.POST.get('fullAddress')
    municipality = request.POST.get('municipality')
    locality = request.POST.get('locality')
    information_sign = request.POST.get('information_sign')
    information_sign_photo = request.POST.get('information_sign_photo')
    photo = request.POST.get('photo')
    url = request.POST.get('url')
    description = request.POST.get('description')
    requisites_and_title = request.POST.get('requisites_and_title')
    owner = request.POST.get('owner')
    management = request.POST.get('management')
    owner_contacts = request.POST.get('owner_contacts')
    has_security_obligation = request.POST.get('has_security_obligation')
    has_passport_OKN = request.POST.get('has_passport_OKN')
    actual_address = request.POST.get('actual_address')
    gen_species_appearance = request.POST.get('gen_species_appearance')
    req_of_approval = request.POST.get('req_of_approval')
    document_on_approved_security = request.POST.get('document_on_approved_security')
    date = request.POST.get('date')


    OKN_in_ensemble = request.POST.get("OKN_in_ensemble")
    affiliation_U = request.POST.get("affiliation_U")
    esp_valuable_object = request.POST.get("esp_valuable_object")
    has_docs_boundaries = request.POST.get("has_docs_boundaries")
    has_docs_of_aprroval = request.POST.get("has_docs_of_aprroval")
    has_rights = request.POST.get("has_rights")
    information_sign_conformity = request.POST.get("information_sign_conformity")

    if request.POST:
        data_row = ObjectInfo.objects.get(id=id_row_data)

        data_row.slug = slug
        data_row.id_openData = id_openData
        data_row.nativeName = nativeName
        data_row.fullAddress = fullAddress
        data_row.municipality = Municipality.objects.get(id=int(municipality))
        data_row.locality = Locality.objects.get(id=locality)
        data_row.OKN_in_ensemble = OKN_in_ensemble
        data_row.information_sign = information_sign
        data_row.information_sign_photo = information_sign_photo
        data_row.information_sign_conformity = information_sign_conformity
        data_row.photo = photo
        data_row.url = url
        data_row.description = description
        data_row.affiliation_U = affiliation_U
        data_row.esp_valuable_object = esp_valuable_object
        data_row.requisites_and_title = requisites_and_title
        data_row.owner = owner
        data_row.management = management
        data_row.has_security_obligation = has_security_obligation
        data_row.has_passport_OKN = has_passport_OKN
        data_row.actual_address = actual_address
        data_row.gen_species_appearance = Species.objects.get(id=gen_species_appearance)
        data_row.has_docs_boundaries = has_docs_boundaries
        data_row.req_of_approval = req_of_approval
        data_row.has_docs_of_aprroval = has_docs_of_aprroval
        data_row.document_on_approved_security = document_on_approved_security
        data_row.has_rights = has_rights

        data_row.date = date
        data_row.save()
        # print(id_openData)
        # print(data_row)

    return HttpResponseRedirect('http://127.0.0.1:8000/dashboard/panel/')
'''


def add_data(request):
    print('in 1')
    text = ''
    if request.POST:
        print('in 2')
        form = ObjectInfoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            text = '''
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              <strong></strong>Data was added.
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            '''
            print(form.cleaned_data)
    else:
        form = ObjectInfoForm()
    return render(request, 'dashboard/add_form.html', {"form": form, "text": text})


def search(request):
    query = request.GET.get('q')
    founded_articles = ObjectInfo.objects.filter(Q(id_openData__icontains=query) | Q(nativeName__icontains=query))
    form = ObjectInfoForm()
    context = {
        "data": founded_articles,
        "form": form
    }
    return render(request, "dashboard/panel.html", context)


def delete_data(request):
    if request.method == 'POST':
        print(request.POST)
        data = request.POST.getlist('for_delete')
        # print(data)
        # print('this is data len:', len(data))
        for id in data:
            ObjectInfo.objects.filter(id=id).delete()

    return HttpResponseRedirect(reverse('panel'))

excelpars/templates/dashboard/add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col">
            <h3>Form</h3>
            {{text|safe}}
            <hr>
            <form enctype="multipart/form-data" action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary">Add</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block jquery %}
<script>
  $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1940:2100",
      // You can put more options here.
      dateFormat: 'yy-mm-dd',
    });
  });
</script>
{% endblock %}

excelpars/templates/dashboard/home.html
{% extends 'base.html' %}

{% block content %}
    {{ text }}
    <a href="{% url 'logout' %}">Logout</a>
{% endblock %}

excelpars/templates/dashboard/jq_code_update_form.html
<script>
  $(".id_data").on('click', function(){
    var id_row = $(this).attr("data-id")
    console.log(id_row)

    data = {
      'id_row': id_row,
    }
    $.ajax({
      type: "GET",
      url: "{% url 'get_id_data'%}",
      data: data,
      dataType: "json",
      success: function(data){
      console.log("This is id data")
        console.log(data)
        console.log(data.fields.nativeName)
        $("#id_row_data").val(data.pk)
        $("#id_slug").val(data.fields.slug)
        $("#id_id_openData").val(data.fields.id_openData)
        $("#id_nativeName").val(data.fields.nativeName)
        $("#id_fullAddress").html(data.fields.fullAddress)
        $("#id_municipality").val(data.fields.municipality)
        $("#id_locality").val(data.fields.locality)


        $("#id_OKN_in_ensemble").val(data.fields.OKN_in_ensemble);

        $("#id_information_sign").val(data.fields.information_sign)

        $("#id_information_sign_photo").attr('src', data.fields.information_sign_photo);

        $("#id_information_sign_conformity").val(data.fields.information_sign_conformity)


        //$("#id_photo").val(data.fields.photo)
        $("#id_url").val(data.fields.url)
        $("#id_description").val(data.fields.description)


          $("#id_affiliation_U").val(data.fields.affiliation_U);


        $("#id_esp_valuable_object").val(data.fields.esp_valuable_object);



        $("#id_requisites_and_title").html(data.fields.requisites_and_title)
        $("#id_owner").val(data.fields.owner)
        $("#id_management").val(data.fields.management)
        $("#id_owner_contacts").val(data.fields.owner_contacts)
        $("#id_has_security_obligation").val(data.fields.has_security_obligation)
        $("#id_has_passport_OKN").val(data.fields.has_passport_OKN)
        $("#id_actual_address").val(data.fields.actual_address)
        $("#id_gen_species_appearance").val(data.fields.gen_species_appearance)
        $("#id_req_of_approval").html(data.fields.req_of_approval)


        $("#id_has_docs_boundaries").val(data.fields.has_docs_boundaries);



        $("#id_has_docs_of_aprroval").val(data.fields.has_docs_of_aprroval);


        $("#id_document_on_approved_security").val(data.fields.document_on_approved_security);


        $("#id_has_rights").val(data.fields.has_rights);


        $("#id_date").val(data.fields.date)
        console.log("Hello world")
      }
    })
  })
</script>

excelpars/templates/dashboard/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <br>
    <br>
    <br>
    <br>
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">login</button>
            </form>
        </div>
        <div class="col-4"></div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</div>


{% endblock %}

excelpars/templates/dashboard/panel.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Panel{% endblock %}

{% block content %}
<div class="container">
    <br>
    <div class="row" style="overflow: scroll">
        <div class="col-12">
            <table class="table" style="font-size:12px">
              <form name="delete_data" action="{% url 'delete_data' %}" method="post">
                {% csrf_token %}
              <thead class="thead-dark">
                <tr>
                  <th><button type="submit" class="btn btn-danger">Delete</button></th>
                  <th scope="col">ID opendata.mkrf.ru</th>
                  <th scope="col">Наименование</th>
                  <th scope="col">Полный адрес</th>
                  <th scope="col">Муниципальное образование</th>
                  <th scope="col">Населенный пункт</th>
                  <th scope="col">ОКН входит в ансамбль (да/нет)</th>
                  <th scope="col">Наличие уcтановленной информационной надписи установленного образца</th>
                  <th scope="col">Фотография информационной надписи</th>
                  <th scope="col">Наличие информационной надписи, но не соответствующей требованиям</th>
                  <th scope="col">Фото</th>
                  <th scope="col">URL адрес</th>
                  <th scope="col">Описание</th>
                  <th scope="col">Принадлежность к ЮНЭСКО</th>
                  <th scope="col">Особо ценный объект</th>
                  <th scope="col">Реквизиты и наименование акта органа государственной власти о постановке на государственную охрану объекта культурного наследия</th>
                  <th scope="col">Собственник</th>
                  <th scope="col">Под чьим управлением</th>
                  <th scope="col">Контактные данные собственника ОКН</th>
                  <th scope="col">Наличие охранного обязательства ОКН</th>
                  <th scope="col">Наличие паспорта ОКН</th>
                  <th scope="col">Актуальный адрес</th>
                  <th scope="col">Общая видовая принадлежность</th>
                  <th scope="col">Наличие документов о границах территории ОКН</th>
                  <th scope="col">Реквизиты об утверждении границ территории:</th>
                  <th scope="col">Наличие документов об утвержденых зонах охраны</th>
                  <th scope="col">Документ об утвержденых зонах охраны</th>
                  <th scope="col">Наличие зарегистрированных прав/обременений</th>
                  <th scope="col">Дата</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
              {% for d in data%}
                <tr>
                  <th><input type="checkbox" name="for_delete" value="{{d.id}}"></th>
                  <th scope="row">{{ d.id_openData }}</th>
                  <td>{{ d.nativeName }}</td>
                  <td>{{ d.fullAddress }}</td>
                  <td>{{ d.municipality }}</td>
                  <td>{{ d.locality }}</td>
                  <td>{{ d.OKN_in_ensemble }}</td>
                  <td>{{ d.information_sign }}</td>
                  <td><img src="/media/{{ d.information_sign_photo }}" style="width:100px"></td>
                  <td>{{ d.information_sign_conformity }}</td>
                  <td><img src="/media/{{ d.photo }}" style="width:100px"></td>
                  <td>{{ d.url }}</td>
                  <td>{{ d.description }}</td>
                  <td>{{ d.affiliation_U }}</td>
                  <td>{{ d.esp_valuable_object }}</td>
                  <td>{{ d.requisites_and_title }}</td>
                  <td>{{ d.owner }}</td>
                  <td>{{ d.management }}</td>
                  <td>{{ d.owner_contacts }}</td>
                  <td>{{ d.has_security_obligation }}</td>
                  <td>{{ d.has_passport_OKN }}</td>
                  <td>{{ d.actual_address }}</td>
                  <td>{{ d.gen_species_appearance }}</td>
                  <td>{{ d.has_docs_boundaries }}</td>
                  <td>{{ d.req_of_approval }}</td>
                  <td>{{ d.has_docs_of_aprroval }}</td>
                  <td>{{ d.document_on_approved_security }}</td>
                  <td>{{ d.has_rights}}</td>
                  <td>{{ d.date }}</td>
                    <td><button type="button" id='id_data' class="btn btn-primary id_data" data-id="{{ d.id }}" data-toggle="modal" data-target="#exampleModal">edit</button></td>
                </tr>
              {% endfor %}
                <!--<tr>-->
                  <!--<th scope="row">2</th>-->
                  <!--<td>Jacob</td>-->
                  <!--<td>Thornton</td>-->
                  <!--<td>@fat</td>-->
                <!--</tr>-->
                <!--<tr>-->
                  <!--<th scope="row">3</th>-->
                  <!--<td>Larry</td>-->
                  <!--<td>the Bird</td>-->
                  <!--<td>@twitter</td>-->
                <!--</tr>-->
              </tbody>
              </form>
            </table>
        </div>
        <div class="col-3"></div>
          <div class="col-6">
            <div class="pagination" style="text-align:center">
                <span class="step-links">
                    {% if data.has_previous %}
                        <a href="?page=1" class="btn btn-info">&laquo; first</a>
                        <a href="?page={{ data.previous_page_number }}" class="btn btn-info">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ data.number }} of {{ data.paginator.num_pages }}.
                    </span>

                    {% if data.has_next %}
                        <a href="?page={{ data.next_page_number }}" class="btn btn-info">next</a>
                        <a href="?page={{ data.paginator.num_pages }}" class="btn btn-info">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
          </div>
          <div class="col-3"></div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form enctype="multipart/form-data"  action="{% url 'edit_data' %}" method="post">
        <div class="modal-body">
            {% csrf_token %}
            <input type="hidden" name="id_row_data" id="id_row_data" value="">
            {{ form|crispy }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Edit</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block jquery %}
<script>
  $('#myModal').on('shown.bs.modal', function () {
    $('#myInput').trigger('focus')
  })


</script>

{% include "dashboard/jq_code_update_form.html" %}

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1940:2100",
      // You can put more options here.
      dateFormat: 'yy-mm-dd',
    });
  });
</script>
{% endblock %}